name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: dash

    env: 
      YT_API_KEY: ${{ secrets.YT_API_KEY }}

    steps:
      - name: OwnerCheck
        run: |
          if [ ${{ github.actor }} != "ThomasvanBommel" ]
          then
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: ./
