name: CI

on:
  push:
    branches:
      - "*"

  workflow_dispatch:

jobs:
  # checkout repository
  checkout:
    runs-on: dash

    steps:
        # check the actor running the workflow (not necessary?)
      - name: OwnerCheck
        run: |
          if [ ${{ github.actor }} != "ThomasvanBommel" ]
          then
            echo "Error wrong actor: ${{ github.actor }}"
            exit 1
          fi

        # checkout repo using github action
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

  # build application before testing
  build:
    needs: checkout

    runs-on: dash

    steps:
      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm test
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}

    # steps:
    #   - name: Build
    #     uses: ./.github/actions/test/
    #     with:
    #       yt_api_key: ${{ secrets.YT_API_KEY }}

  # test:
  #   needs: build

  #   runs-on: dash

  #   steps:
  #     - name: Test
  #       run: npm test
  #       env:
  #         YT_API_KEY: ${{ secrets.YT_API_KEY }}

