name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: dash

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: ./
