name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: dash

    steps:
      - name: Test
        uses: thomasvanbommel/action
        run: ls -a

      - name: Build
        run: echo "building..."

