name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: dash

    steps:
      - uses: actions/checkout@v1

      - name: Build
        uses: ./github/actions

