name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: dash

    env: 
      YT_API_KEY: ${{ secrets.YT_API_KEY }}

    steps:
      - name: OwnerCheck
        run: |
          echo ${{ github.actor }} && exit 1

      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: ./
