name: CI

on:
  push:
    branches:
      - "*"

  workflow_dispatch:

jobs:
  # checkout repository
  testing:
    runs-on: dash

    steps:
        # check the actor running the workflow (not necessary?)
      - name: OwnerCheck
        run: |
          if [ ${{ github.actor }} != "ThomasvanBommel" ]
          then
            echo "Error wrong actor: ${{ github.actor }}"
            exit 1
          fi

        # checkout repo using github action
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm i

      - run: npm start -- test
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}

      - run: npm test
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}

